# ctwrap conda package dependencies
name: ctwrap
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - h5py
  - pint
  - ruamel.yaml>=0.17.0
  - pandas>=1.4
  - cantera>=3.1  # installed from conda-forge
  - setuptools
  - pytest
  - pytest-cov
  - coverage
  - ipython
  - jupyter
  - matplotlib
  - pandoc  # needed for nbsphinx to process Jupyter notebooks  #TODO add to docs env only
