name: "Pull Request Checks"

on:
  pull_request:
    # Build when a pull request targets main
    branches:
      - main

jobs:
  nosetests-linux:
    name: Run pytest on Linux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml
        activate-environment: ctwrap
        use-mamba: true
        auto-update-conda: true
        auto-activate-base: false
        python-version: "3.11"
    - name: Install package
      shell: bash -l {0}
      run: |
        pip install -e .
    - name: Run pytest
      shell: bash -l {0}
      run: |
        pytest -q

  sphinx-docs:
    name: Check sphinx docs on Linux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml
        activate-environment: ctwrap
        use-mamba: true
        auto-update-conda: true
        auto-activate-base: false
        python-version: "3.11"
    - name: Install project and docs requirements
      shell: bash -l {0}
      run: |
        pip install -e .
        pip install -r docs/requirements.txt
    - name: Build Sphinx HTML
      shell: bash -l {0}
      run: |
        sphinx-build -b html docs docs/_build/html
    - name: Upload docs artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs-html
        path: docs/_build/html
